apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/luis-fnogueira/ws-stack-dados-k8s.git'
    path: infra/src/helm-charts/minio-tenant
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'arn:aws:eks:us-east-1:910792074719:cluster/cluster-npoprod'
      namespace: example-minio
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
