# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
postgresql:
  enabled: false
  host: ~
  port: 5432
  auth:
    postgresPassword: "postgres"
    database: "metastore"
    username: "hive"
    password: "hive"

image:
  repository: 5200710/hive
  tag: 3.1.3
#  pullPolicy: Always

resources: { }
conf:
    # if not set, default hive.metastore.warehouse.dir is default to: "hdfs://{{.Release.Name}}-hdfs:8020/user/hive/warehouse"
    # hive.metastore.warehouse.dir: hdfs://my-hdfs.bigdata.svc.cluster.local:9820/user/hive/warehouse
    # hive.metastore.schema.verification: false
  hiveSite:
    hive_metastore_uris: thrift://hive-metastore:9083
    hive.metastore.warehouse.dir: s3a://metastore/warehouse/
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.access.key: data-lake
    fs.s3a.secret.key: 12620ee6-2162-11ee-be56-0242ac120002
    fs.s3a.endpoint: http://minio.deepstorage.svc.Cluster.local
    fs.s3a.path.style.access: true
    fs.s3a.connection.ssl.enabled: false


env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: hive-metastore-secret-key
        key: password